have_fun: false
memory_config:
  disabled: false
code_review:
  disable: false
  comment_severity_threshold: LOW
  max_review_comments: -1
  pull_request_opened:
    help: false
    summary: true
    code_review: true
    include_drafts: true
ignore_patterns:
  - "*.otbm"
  - "*.otmm"
  - "*.dat"
  - "*.spr"
  - "build/**"
  - "build_conan/**"
  - ".vcpkg_installed/**"
